# Generated by Django 5.2.7 on 2025-10-19 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxyServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=255, verbose_name="主机地址")),
                ("port", models.IntegerField(verbose_name="端口")),
                (
                    "username",
                    models.CharField(blank=True, max_length=100, verbose_name="用户名"),
                ),
                (
                    "password",
                    models.CharField(blank=True, max_length=100, verbose_name="密码"),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("http", "HTTP"),
                            ("https", "HTTPS"),
                            ("socks5", "SOCKS5"),
                        ],
                        default="http",
                        max_length=10,
                        verbose_name="协议",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "可用"),
                            ("inactive", "不可用"),
                            ("testing", "测试中"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="响应时间(ms)"
                    ),
                ),
                (
                    "last_tested",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后测试时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "代理服务器",
                "verbose_name_plural": "代理服务器",
                "unique_together": {("host", "port")},
            },
        ),
        migrations.CreateModel(
            name="SpiderTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="任务名称")),
                ("description", models.TextField(blank=True, verbose_name="任务描述")),
                ("keywords", models.CharField(max_length=255, verbose_name="关键词")),
                (
                    "seed_urls",
                    models.TextField(help_text="JSON格式存储", verbose_name="种子URL"),
                ),
                (
                    "max_pages",
                    models.IntegerField(default=100, verbose_name="最大页数"),
                ),
                ("max_depth", models.IntegerField(default=3, verbose_name="最大深度")),
                (
                    "concurrent_requests",
                    models.IntegerField(default=5, verbose_name="并发请求数"),
                ),
                (
                    "download_delay",
                    models.FloatField(default=1.0, verbose_name="下载延迟(秒)"),
                ),
                (
                    "timeout",
                    models.IntegerField(default=30, verbose_name="超时时间(秒)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "已创建"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("paused", "暂停"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "爬虫任务",
                "verbose_name_plural": "爬虫任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrawledPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2000, verbose_name="页面URL")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="页面标题"
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="页面内容")),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="HTTP状态码"
                    ),
                ),
                ("depth", models.IntegerField(default=0, verbose_name="爬取深度")),
                (
                    "parent_url",
                    models.URLField(
                        blank=True, max_length=2000, verbose_name="父页面URL"
                    ),
                ),
                (
                    "crawled_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="爬取时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crawled_pages",
                        to="spider_core.spidertask",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "爬取页面",
                "verbose_name_plural": "爬取页面",
                "ordering": ["-crawled_at"],
                "unique_together": {("task", "url")},
            },
        ),
    ]
