# Generated by Django 5.2.7 on 2025-10-20 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spider_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawledResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="页面标题")),
                ("url", models.URLField(max_length=2000, verbose_name="页面URL")),
                ("description", models.TextField(blank=True, verbose_name="页面描述")),
                (
                    "crawled_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="爬取时间"),
                ),
            ],
            options={
                "verbose_name": "爬取结果",
                "verbose_name_plural": "爬取结果",
                "ordering": ["-crawled_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="crawledpage",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="crawledpage",
            name="task",
        ),
        migrations.DeleteModel(
            name="ProxyServer",
        ),
        migrations.RemoveField(
            model_name="spidertask",
            name="concurrent_requests",
        ),
        migrations.RemoveField(
            model_name="spidertask",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="spidertask",
            name="description",
        ),
        migrations.RemoveField(
            model_name="spidertask",
            name="download_delay",
        ),
        migrations.RemoveField(
            model_name="spidertask",
            name="max_depth",
        ),
        migrations.RemoveField(
            model_name="spidertask",
            name="seed_urls",
        ),
        migrations.RemoveField(
            model_name="spidertask",
            name="timeout",
        ),
        migrations.RemoveField(
            model_name="spidertask",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="spidertask",
            name="search_engine",
            field=models.CharField(
                choices=[("bing", "Bing"), ("baidu", "百度")],
                default="bing",
                max_length=10,
                verbose_name="搜索引擎",
            ),
        ),
        migrations.AlterField(
            model_name="spidertask",
            name="keywords",
            field=models.CharField(max_length=255, verbose_name="搜索关键词"),
        ),
        migrations.AlterField(
            model_name="spidertask",
            name="max_pages",
            field=models.IntegerField(default=1, verbose_name="搜索页数"),
        ),
        migrations.AlterField(
            model_name="spidertask",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "已创建"),
                    ("running", "运行中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                ],
                default="created",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AddField(
            model_name="crawledresult",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="spider_core.spidertask",
                verbose_name="所属任务",
            ),
        ),
        migrations.DeleteModel(
            name="CrawledPage",
        ),
        migrations.AlterUniqueTogether(
            name="crawledresult",
            unique_together={("task", "url")},
        ),
    ]
